version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-/api}
        REACT_APP_WS_URL: ${REACT_APP_WS_URL:-}
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_CONTAINER_PORT:-3000}"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NGINX_PORT=${FRONTEND_CONTAINER_PORT:-3000}
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL:-/api}
      - REACT_APP_WS_URL=${REACT_APP_WS_URL:-}
      - BACKEND_SERVICE_HOST=${BACKEND_SERVICE_HOST:-backend}
      - BACKEND_SERVICE_PORT=${BACKEND_CONTAINER_PORT:-8001}
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-40s}

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        APP_UID: ${APP_UID:-1000}
        APP_GID: ${APP_GID:-1000}
    ports:
      - "${BACKEND_PORT:-8001}:${BACKEND_CONTAINER_PORT:-8001}"
    env_file:
      - ./backend/.env
    environment:
      - APP_UID=${APP_UID:-}
      - APP_GID=${APP_GID:-}
      - HOST=${BACKEND_BIND_HOST:-0.0.0.0}
      - PORT=${BACKEND_CONTAINER_PORT:-8001}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000,http://192.168.56.1:3000}
      - CREWS_PATH=${CREWS_PATH:-/app/crews}
      - SOCKET_PING_TIMEOUT=${SOCKET_PING_TIMEOUT:-60}
      - SOCKET_PING_INTERVAL=${SOCKET_PING_INTERVAL:-25}
      - SOCKET_MAX_HTTP_BUFFER_SIZE=${SOCKET_MAX_HTTP_BUFFER_SIZE:-100000000}
    volumes:
      - ./crews:/app/crews
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_CONTAINER_PORT:-8001}/api/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-40s}

networks:
  default:
    name: ${NETWORK_NAME:-crewai-network}
