version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_CONTAINER_PORT:-3000}"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL:-http://localhost:8001/api}
      - REACT_APP_WS_URL=${REACT_APP_WS_URL:-http://localhost:8001}
      - PORT=${FRONTEND_CONTAINER_PORT:-3000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ${FRONTEND_DEV_COMMAND:-npm run dev}
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        APP_UID: ${APP_UID:-1000}
        APP_GID: ${APP_GID:-1000}
    ports:
      - "${BACKEND_PORT:-8001}:${BACKEND_CONTAINER_PORT:-8001}"
    env_file:
      - ./backend/.env
    environment:
      - APP_UID=${APP_UID:-}
      - APP_GID=${APP_GID:-}
      - HOST=${BACKEND_BIND_HOST:-0.0.0.0}
      - PORT=${BACKEND_CONTAINER_PORT:-8001}
      - LOG_LEVEL=${LOG_LEVEL_DEV:-debug}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000,http://192.168.56.1:3000}
      - CREWS_PATH=${CREWS_PATH:-/app/crews}
      - SOCKET_PING_TIMEOUT=${SOCKET_PING_TIMEOUT:-60}
      - SOCKET_PING_INTERVAL=${SOCKET_PING_INTERVAL:-25}
      - SOCKET_MAX_HTTP_BUFFER_SIZE=${SOCKET_MAX_HTTP_BUFFER_SIZE:-100000000}
      - RELOAD=${RELOAD:-true}
    volumes:
      - ./backend:/app
      - ./crews:/app/crews
    command: uvicorn main:app --host ${BACKEND_BIND_HOST:-0.0.0.0} --port ${BACKEND_CONTAINER_PORT:-8001} --reload

networks:
  default:
    name: ${NETWORK_NAME_DEV:-crewai-network-dev}
